#!/bin/bash

# bashrc doesn't work due of the non-interactive check
for i in ~/.bash/*; do
	source $i
done
[ -f ~/.bashrc.local ] && source ~/.bashrc.local
IFS=:
(
	stest -flx $PATH
	compgen -A function
	alias | awk -F '[ =]' '{print $2}'
) \
| sort -u | dmenu "$@" | source /dev/stdin
