#!/usr/bin/env zsh

# Make also functions and aliases executeable

# make sure aliases are executed correctly
# bash
#shopt -s expand_aliases

# bashrc doesn't work due of the non-interactive check
#if [ -d $HOME/.bash ]; then
#    for i in $HOME/.bash/*; do
#        source "$i"
#    done
#fi

[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"

(
    #stest -flx "$PATH"
    #compgen -A function
    #compgen -c
    #alias | awk -F '[ =]' '{print $2}'
    alias | awk -F '[ =]' '{print $1}'
) \
| sort -u
