#!/bin/bash
alias diary='vim -c "call vimwiki#diary#make_note(v:count1)"'
alias vimwiki='vim -c "VimwikiIndex"'
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
if [ "$(uname)" != 'Darwin' ]; then
    alias ps='ps -H'
    alias zcat='gunzip -c'
fi
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
