#!/bin/bash

# shellcheck disable=SC1091
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

if [ -d /etc/bash_completion.d ]; then
    for file in /etc/bash_completion.d/*; do
        # broken in ubuntu
        if [ "$(lsb_release -i -s)" = "Ubuntu" ]; then
            bn=$(basename "$file")
            if [ "$bn" = "grub" ] || [ "$bn" = "openvpn" ]; then
                continue
            fi
        fi
        if [ "$(lsb_release -i -s)" = "Debian" ]; then
            bn=$(basename "$file")
            if [ "$bn" = "debconf" ] || [ "$bn" = "grub" ] || [ "$bn" = "insserv" ]; then
                continue
            fi
        fi
        # shellcheck disable=SC1090
        source "$file"
    done
fi
