#!/bin/bash

# delete git branch
deletebranch(){
	echo git checkout $1
	echo git pull
	echo git checkout master
	echo git pull
	echo git branch -d $1
	echo git push origin :$1
}


encfs.pwd.sh() {
	encfs $(pwd)/encrypted $(pwd)/decrypted
}

# generate random passwords
genpasswd() {
	local l=$1
	[ "$l" = "" ] && l=32
	tr -dc 'A-Za-z0-9!@#$%^&*_()-' < /dev/urandom | head -c ${l} | xargs
}

# leo
leo() {
    lang=en
    IFS=+
    Q="${*// /%20}"
     w3m -dump "https://dict.leo.org/${lang}de/?search=${Q//+/%20}" \
        | grep -EA 900 'Aktivieren Sie Javascript' \
        | grep -EB 900 'Weitere Aktionen' \
        | sed '/Weitere Aktionen/d' \
        | tail -n+5 \
        | less
}

# create new gitbranch
newbranch(){
	echo git checkout master
	echo git pull
	echo git checkout -b $1
	echo git push -u origin $1
}
