#!/bin/bash
if infocmp xterm-256color >/dev/null 2>&1; then
    export TERM='xterm-256color'
fi

# user@hostname
if [[ -n "$SSH_CLIENT" ]]; then
    PROMPT_USER_HOST="${USER}@\h:"
else
    PROMPT_USER_HOST=""
fi

# current pwd
_prompt_pwd() {
    # bold, to get nicer blue color
    echo "$(pwd | perl -pe "s|^$HOME|~|g; s|/([^/])[^/]*(?=/)|/\$1|g")/"
}

# git status
_prompt_git_status() {
  INDEX=$(git status --porcelain 2> /dev/null)
  if [[ -n "$INDEX" ]]; then
    echo "*"
  fi
}

# git branch
_prompt_git_info() {
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
    ref="${ref/feat/ft}"
    echo " [${ref#refs/heads/}]"
}

# Colors from https://github.com/jessfraz/dotfiles/blob/master/.bash_prompt
# and added grey
if tput setaf 1 &> /dev/null; then
	tput sgr0; # reset colors
	bold=$(tput bold);
	reset=$(tput sgr0);
	# Solarized colors, taken from http://git.io/solarized-colors.
	black=$(tput setaf 0);
	blue=$(tput setaf 33);
	cyan=$(tput setaf 37);
	green=$(tput setaf 64);
	orange=$(tput setaf 166);
	purple=$(tput setaf 125);
	red=$(tput setaf 124);
	violet=$(tput setaf 61);
	white=$(tput setaf 15);
	yellow=$(tput setaf 136);
	grey=$(tput setaf 244);
else
	bold='';
	reset="\e[0m";
	# shellcheck disable=SC2034
	black="\e[1;30m";
	blue="\e[1;34m";
	cyan="\e[1;36m";
	green="\e[1;32m";
	# shellcheck disable=SC2034
	orange="\e[1;33m";
	# shellcheck disable=SC2034
	purple="\e[1;35m";
	red="\e[1;31m";
	violet="\e[1;35m";
	white="\e[1;37m";
	yellow="\e[1;33m";
	grey="\e[1;37m";
fi;

PS1="${PROMPT_USER_HOST}"
PS1+="\[${blue}\]\$(_prompt_pwd)"
PS1+="\[${grey}\]\$(_prompt_git_info)"
PS1+="\[${red}\]\$(_prompt_git_status)"
PS1+="\[${grey}\]\$ "
export PS1
